-- MySQL Script generated by MySQL Workbench
-- Mon Jan 28 20:09:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sim-eurosan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sim-eurosan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sim-eurosan` DEFAULT CHARACTER SET utf8 ;
USE `sim-eurosan` ;

-- -----------------------------------------------------
-- Table `sim-eurosan`.`fw_mark_counter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sim-eurosan`.`fw_mark_counter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `listing` VARCHAR(50) NOT NULL,
  `keyname` VARCHAR(50) NOT NULL,
  `value` VARCHAR(256) NOT NULL,
  `created` BIGINT NOT NULL,
  `expire` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fw_mark_counter_listing_keyname_created_desc_idx` (`listing` ASC, `keyname` ASC, `created` DESC),
  INDEX `fw_mark_counter_listing_keyname_created_idx` (`listing` ASC, `keyname` ASC, `created` ASC),
  INDEX `fw_mark_counter_listing_keyname_idx` (`listing` ASC, `keyname` ASC),
  INDEX `fw_mark_counter_listing_keyname_expire_idx` (`listing` ASC, `keyname` ASC, `expire` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sim-eurosan`.`fw_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sim-eurosan`.`fw_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `pass` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(50) NOT NULL,
  `locale` VARCHAR(10) NULL DEFAULT NULL,
  `timezone` VARCHAR(255) NULL DEFAULT NULL,
  `status` TINYINT NULL,
  `image` VARCHAR(16) NULL,
  `full_name` VARCHAR(255) NULL,
  `phone` VARCHAR(25) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fw_user_email_unq` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sim-eurosan`.`fw_repo_bucket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sim-eurosan`.`fw_repo_bucket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(50) NOT NULL,
  `path` VARCHAR(16) NOT NULL,
  `bytes` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fw_repo_bucket_path_unq` (`path` ASC),
  UNIQUE INDEX `fw_repo_bucket_uid_unq` (`uid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sim-eurosan`.`fw_repo_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sim-eurosan`.`fw_repo_file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bucket_id` INT NOT NULL,
  `uid` VARCHAR(50) NOT NULL,
  `path` VARCHAR(16) NOT NULL,
  `filename` VARCHAR(250) NOT NULL,
  `extension` VARCHAR(10) NOT NULL,
  `bytes` INT NOT NULL,
  `creation_user` INT NOT NULL,
  `creation_time` BIGINT NOT NULL,
  `modification_time` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fw_repo_file_bucket_id_uid_unq` (`bucket_id` ASC, `uid` ASC),
  UNIQUE INDEX `fw_repo_file_path_unq` (`path` ASC),
  INDEX `fw_repo_file_creation_user_idx` (`creation_user` ASC),
  CONSTRAINT `fw_repo_file_bucket_id`
    FOREIGN KEY (`bucket_id`)
    REFERENCES `sim-eurosan`.`fw_repo_bucket` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fw_repo_file_fw_user_id`
    FOREIGN KEY (`creation_user`)
    REFERENCES `sim-eurosan`.`fw_user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

USE `sim-eurosan` ;

-- -----------------------------------------------------
-- Placeholder table for view `sim-eurosan`.`view_fw_repo_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sim-eurosan`.`view_fw_repo_file` (`bucket_id` INT, `bucket_uid` INT, `bucket_path` INT, `file_id` INT, `file_uid` INT, `file_extension` INT, `file_bytes` INT, `file_filename` INT, `file_path` INT);

-- -----------------------------------------------------
-- View `sim-eurosan`.`view_fw_repo_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sim-eurosan`.`view_fw_repo_file`;
USE `sim-eurosan`;
CREATE  OR REPLACE VIEW `view_fw_repo_file` as
SELECT
	bucket.id      as bucket_id,
	bucket.uid     as bucket_uid,
    bucket.path    as bucket_path,
    file.id        as file_id,
    file.uid       as file_uid,
	file.extension as file_extension,
    file.bytes     as file_bytes,
    file.filename  as file_filename,
    file.path      as file_path
FROM fw_repo_file as file
INNER JOIN fw_repo_bucket as bucket
   ON file.bucket_id = bucket.id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
